name: dotnet format

on:
    pull_request:
        branches: [main, development]

jobs:
    check-format:
        runs-on: ubuntu-latest
        steps:
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "5.0.x"

            - name: Install dotnet-format tool
              run: dotnet tool install -g dotnet-format

            - name: Check out code
              uses: actions/checkout@v2

            - name: Run dotnet format
              working-directory: ./frontend
              run: dotnet format 
