name: .NET

on:
    pull_request:
        branches: [main, development]

jobs:
    build:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Test
              run: dotnet test --no-build --verbosity normal
            - name: Install dotnet-format tool
              run: dotnet tool install -g dotnet-format
            - name: Run dotnet format
              run: dotnet format --check --verbosity diagnostic
