name: Format check on pull request
on:
    pull_request:
        branches: [main, development]

jobs:
    dotnet-format-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
        
            - name: Install dotnet-format tool
              run: dotnet tool install -g dotnet-format --version 5.1.250801

            - name: Run dotnet format
              id: format
              uses: xt0rted/dotnet-format@v1.2.0
              with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                action: "fix"
                only-changed-files: true

            - name: Commit files
              if: steps.format.outputs.has-changes == 'true'
              uses: EndBug/add-and-commit@v7.4.0
              with:
                  author_name: Github Actions
                  author_email: actions@github.com
                  message: Automated dotnet-format update
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    dotnet-format-server:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install dotnet-format tool
              run: dotnet tool install -g dotnet-format --version 5.1.250801

            - name: Run dotnet format
              id: format
              uses: xt0rted/dotnet-format@v1.2.0
              with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                action: "fix"
                only-changed-files: true

            - name: Verify Changed files
              uses: tj-actions/verify-changed-files@v8.2

            - name: Commit files
              if: steps.format.outputs.has-changes == 'true'
              uses: EndBug/add-and-commit@v7.4.0
              with:
                  author_name: Github Actions
                  author_email: actions@github.com
                  message: Automated dotnet-format update
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
