name: "TODO to Issue"
# TODO test
on:
    push:
        branches: [development]
jobs:
    build:
        runs-on: "ubuntu-latest"
        defaults:
          run:
            working-directory: ./server
        steps:
            - uses: "actions/checkout@master"
            - name: "TODO to Issue"
              uses: "alstr/todo-to-issue-action@v4.3"
              id: "todo"
              with:
                PROJECTS_SECRET: ${{ secrets.PROJECTS_SECRET }}
